apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pl-cloud
    db: pgsql
  name: cron-script-server
spec:
  selector:
    matchLabels:
      app: pl-cloud
      name: cron-script-server
  template:
    metadata:
      labels:
        app: pl-cloud
        name: cron-script-server
    spec:
      containers:
      - env:
        - name: PL_JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              key: jwt-signing-key
              name: cloud-auth-secrets
        - name: PL_POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              key: PL_POSTGRES_USERNAME
              name: pl-db-secrets
        - name: PL_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PL_POSTGRES_PASSWORD
              name: pl-db-secrets
        - name: PL_DATABASE_KEY
          valueFrom:
            secretKeyRef:
              key: database-key
              name: pl-db-secrets
        - name: PL_VZMGR_SERVICE
          valueFrom:
            configMapKeyRef:
              key: PL_VZMGR_SERVICE
              name: pl-service-config
        envFrom:
        - configMapRef:
            name: pl-db-config
        - configMapRef:
            name: pl-tls-config
        - configMapRef:
            name: pl-domain-config
        image: gcr.io/pixie-oss/pixie-prod/cloud/cron_script_server_image:latest
        livenessProbe:
          httpGet:
            path: /healthz
            port: 50700
            scheme: HTTPS
        name: cron-script-server
        ports:
        - containerPort: 50700
          name: http2
        - containerPort: 50701
          name: metrics-http
        readinessProbe:
          httpGet:
            path: /healthz
            port: 50700
            scheme: HTTPS
        volumeMounts:
        - mountPath: /certs
          name: certs
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
      - name: certs
        secret:
          secretName: service-tls-certs