apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: pl-cloud
    component: cloud-deps
  name: plc:stan-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: plc:stan
subjects:
- kind: ServiceAccount
  name: stan
  namespace: plc