apiVersion: v1
kind: Service
metadata:
  labels:
    app: pl-cloud
    component: cloud-deps
    name: pl-stan
  name: pl-stan
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 7777
  selector:
    app: pl-cloud
    component: cloud-deps
    name: pl-stan