apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pl-cloud
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pl-cloud
      name: api-server
  template:
    metadata:
      labels:
        app: pl-cloud
        name: api-server
    spec:
      containers:
      - env:
        - name: PL_JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              key: jwt-signing-key
              name: cloud-auth-secrets
        - name: PL_SESSION_KEY
          valueFrom:
            secretKeyRef:
              key: session-key
              name: cloud-session-secrets
        - name: PL_VZMGR_SERVICE
          valueFrom:
            configMapKeyRef:
              key: PL_VZMGR_SERVICE
              name: pl-service-config
        - name: PL_AUTH_SERVICE
          valueFrom:
            configMapKeyRef:
              key: PL_AUTH_SERVICE
              name: pl-service-config
        - name: PL_PLUGIN_SERVICE
          valueFrom:
            configMapKeyRef:
              key: PL_PLUGIN_SERVICE
              name: pl-service-config
        - name: PL_PROJECT_MANAGER_SERVICE
          valueFrom:
            configMapKeyRef:
              key: PL_PROJECT_MANAGER_SERVICE
              name: pl-service-config
        - name: PL_PROFILE_SERVICE
          valueFrom:
            configMapKeyRef:
              key: PL_PROFILE_SERVICE
              name: pl-service-config
        - name: PL_ARTIFACT_TRACKER_SERVICE
          valueFrom:
            configMapKeyRef:
              key: PL_ARTIFACT_TRACKER_SERVICE
              name: pl-service-config
        - name: PL_ELASTIC_SERVICE
          valueFrom:
            configMapKeyRef:
              key: PL_ELASTIC_SERVICE
              name: pl-service-config
        - name: PL_MD_INDEX_NAME
          valueFrom:
            configMapKeyRef:
              key: PL_MD_INDEX_NAME
              name: pl-indexer-config
        - name: PL_CONFIG_MANAGER_SERVICE
          valueFrom:
            configMapKeyRef:
              key: PL_CONFIG_MANAGER_SERVICE
              name: pl-service-config
        - name: PL_SEGMENT_WRITE_KEY
          valueFrom:
            configMapKeyRef:
              key: write-key
              name: segment-config
        - name: PL_CRON_SCRIPT_SERVICE
          valueFrom:
            configMapKeyRef:
              key: PL_CRON_SCRIPT_SERVICE
              name: pl-service-config
        - name: PL_VIZIER_IMAGE_SECRET_PATH
          value: /vizier-image-secret
        - name: PL_VIZIER_IMAGE_SECRET_FILE
          value: vizier_image_secret.json
        - name: PL_ELASTIC_USERNAME
          value: elastic
        - name: PL_ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: elastic-config-credentials
        - name: PL_ELASTIC_CA_CERT
          value: /certs/ca.crt
        - name: PL_WORK_DOMAIN
          value: work.$(PL_DOMAIN_NAME)
        - name: PL_KRATOS_BROWSER_URL
          value: https://$(PL_WORK_DOMAIN)/oauth/kratos
        - name: PL_HYDRA_BROWSER_URL
          value: https://$(PL_WORK_DOMAIN)/oauth/hydra
        envFrom:
        - configMapRef:
            name: pl-tls-config
        - configMapRef:
            name: pl-domain-config
        - configMapRef:
            name: pl-ory-service-config
        - configMapRef:
            name: pl-auth-connector-config
        - configMapRef:
            name: pl-errors-config
            optional: true
        image: gcr.io/pixie-oss/pixie-prod/cloud/api_server_image:latest
        livenessProbe:
          httpGet:
            path: /healthz
            port: 51200
            scheme: HTTPS
        name: api-server
        ports:
        - containerPort: 51200
          name: http2
        - containerPort: 51201
          name: metrics-http
        readinessProbe:
          httpGet:
            path: /healthz
            port: 51200
            scheme: HTTPS
        volumeMounts:
        - mountPath: /certs
          name: certs
        - mountPath: /vizier-image-secret
          name: vizier-image-secret
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
      - name: certs
        secret:
          secretName: service-tls-certs
      - name: vizier-image-secret
        secret:
          optional: true
          secretName: vizier-image-secret
      - configMap:
          name: proxy-envoy-config
        name: envoy-yaml