apiVersion: v1
kind: Service
metadata:
  labels:
    app: pl-cloud
  name: api-service
spec:
  ports:
  - name: tcp-http2
    port: 51200
    protocol: TCP
    targetPort: 51200
  selector:
    app: pl-cloud
    name: api-server
  type: ClusterIP