apiVersion: v1
kind: Service
metadata:
  labels:
    app: pl-cloud
  name: project-manager-service
spec:
  clusterIP: None
  ports:
  - name: tcp-http2
    port: 50300
    protocol: TCP
    targetPort: 50300
  selector:
    app: pl-cloud
    name: project-manager-server
  type: ClusterIP