apiVersion: v1
kind: Service
metadata:
  labels:
    app: pl-cloud
  name: vzmgr-service
spec:
  clusterIP: None
  ports:
  - name: tcp-http2
    port: 51800
    protocol: TCP
    targetPort: 51800
  selector:
    app: pl-cloud
    name: vzmgr-server
  type: ClusterIP