apiVersion: v1
data:
  PL_ARTIFACT_BUCKET: pixie-prod-artifacts
  PL_RELEASE_ARTIFACT_BUCKET: pixie-dev-public
  PL_SA_KEY_PATH: /creds/service_account.json
kind: ConfigMap
metadata:
  labels:
    app: pl-cloud
  name: pl-artifact-config