apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pl-cloud
  name: config-manager-server
spec:
  selector:
    matchLabels:
      app: pl-cloud
      name: config-manager-server
  template:
    metadata:
      labels:
        app: pl-cloud
        name: config-manager-server
    spec:
      containers:
      - env:
        - name: PL_JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              key: jwt-signing-key
              name: cloud-auth-secrets
        - name: PL_ARTIFACT_TRACKER_SERVICE
          valueFrom:
            configMapKeyRef:
              key: PL_ARTIFACT_TRACKER_SERVICE
              name: pl-service-config
        - name: PL_VZMGR_SERVICE
          valueFrom:
            configMapKeyRef:
              key: PL_VZMGR_SERVICE
              name: pl-service-config
        - name: PL_PROD_SENTRY
          valueFrom:
            configMapKeyRef:
              key: PL_PROD_SENTRY
              name: pl-sentry-dsn-config
        - name: PL_DEV_SENTRY
          valueFrom:
            configMapKeyRef:
              key: PL_DEV_SENTRY
              name: pl-sentry-dsn-config
        - name: PL_LD_SDK_KEY
          valueFrom:
            configMapKeyRef:
              key: PL_LD_SDK_KEY
              name: pl-ld-config
              optional: true
        envFrom:
        - configMapRef:
            name: pl-tls-config
        - configMapRef:
            name: pl-domain-config
        image: gcr.io/pixie-oss/pixie-prod/cloud/config_manager_server_image:latest
        livenessProbe:
          httpGet:
            path: /healthz
            port: 50500
            scheme: HTTPS
        name: config-manager-server
        ports:
        - containerPort: 50500
          name: http2
        - containerPort: 50501
          name: metrics-http
        readinessProbe:
          httpGet:
            path: /healthz
            port: 50500
            scheme: HTTPS
        volumeMounts:
        - mountPath: /certs
          name: certs
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
      - name: certs
        secret:
          secretName: service-tls-certs