apiVersion: v1
kind: Service
metadata:
  labels:
    app: pl-cloud
  name: config-manager-service
spec:
  clusterIP: None
  ports:
  - name: tcp-http2
    port: 50500
    protocol: TCP
    targetPort: 50500
  selector:
    app: pl-cloud
    name: config-manager-server
  type: ClusterIP