apiVersion: v1
data:
  PL_API_SERVICE_HTTP: api-service.plc:51200
  PL_ARTIFACT_TRACKER_SERVICE: kubernetes:///artifact-tracker-service.plc:50750
  PL_AUTH_SERVICE: kubernetes:///auth-service.plc:50100
  PL_CONFIG_MANAGER_SERVICE: kubernetes:///config-manager-service.plc:50500
  PL_CRON_SCRIPT_SERVICE: kubernetes:///cron-script-service.plc:50700
  PL_ELASTIC_SERVICE: {{ include "configMapValue" .Values.elasticsearch.connectionUrl }}
  PL_PLUGIN_SERVICE: kubernetes:///plugin-service.plc:50600
  PL_PROFILE_SERVICE: kubernetes:///profile-service.plc:51500
  PL_PROJECT_MANAGER_SERVICE: kubernetes:///project-manager-service.plc:50300
  PL_SCRIPTMGR_SERVICE: kubernetes:///scriptmgr-service.plc:52000
  PL_VZMGR_SERVICE: kubernetes:///vzmgr-service.plc:51800
kind: ConfigMap
metadata:
  labels:
    app: pl-cloud
  name: pl-service-config