apiVersion: v1
kind: Service
metadata:
  labels:
    app: pl-cloud
  name: plugin-service
spec:
  clusterIP: None
  ports:
  - name: tcp-http2
    port: 50600
    protocol: TCP
    targetPort: 50600
  selector:
    app: pl-cloud
    name: plugin-server
  type: ClusterIP