apiVersion: v1
data:
  ANNOUNCE_WIDGET_URL: ""
  ANNOUNCEMENT_ENABLED: "false"
kind: ConfigMap
metadata:
  labels:
    app: pl-cloud
  name: pl-announcement-config
---
apiVersion: v1
data:
  CONTACT_ENABLED: "false"
kind: ConfigMap
metadata:
  labels:
    app: pl-cloud
  name: pl-contact-config
---
apiVersion: v1
data:
  ANALYTICS_ENABLED: "false"
kind: ConfigMap
metadata:
  labels:
    app: pl-cloud
  name: pl-analytics-config