apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: internal
  labels:
    app: pl-cloud
  name: cloud-proxy-service
spec:
  ports:
  - name: tcp-https
    port: 443
    protocol: TCP
    targetPort: 56000
  - name: tcp-grcp-web
    port: 4444
    protocol: TCP
    targetPort: 56004
  - name: tcp-http2
    port: 5555
    protocol: TCP
    targetPort: 56000
  selector:
    app: pl-cloud
    name: cloud-proxy-server
  type: LoadBalancer