apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: pl-cloud
  name: create-admin-job
spec:
  template:
    metadata:
      labels:
        app: pl-cloud
    spec:
      containers:
      - env:
        - name: PL_JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              key: jwt-signing-key
              name: cloud-auth-secrets
        - name: PL_PROFILE_SERVICE
          valueFrom:
            configMapKeyRef:
              key: PL_PROFILE_SERVICE
              name: pl-service-config
        - name: PL_AUTH_SERVICE
          valueFrom:
            configMapKeyRef:
              key: PL_AUTH_SERVICE
              name: pl-service-config
        envFrom:
        - configMapRef:
            name: pl-tls-config
        - configMapRef:
            name: pl-domain-config
        - configMapRef:
            name: pl-ory-service-config
        image: gcr.io/pixie-oss/pixie-prod/cloud/job/create_admin_job_image:latest
        name: create-admin-job
        volumeMounts:
        - mountPath: /certs
          name: certs
      initContainers:
      - command:
        - sh
        - -c
        - 'set -x; URL="${PL_KRATOS_PUBLIC_HOST}/health/ready"; until [ $(curl -m
          0.5 -s -o /dev/null -w "%{http_code}" -k ${URL}) -eq 200 ]; do echo "waiting
          for ${URL}" sleep 2; done; '
        env:
        - name: PL_KRATOS_PUBLIC_HOST
          valueFrom:
            configMapKeyRef:
              key: PL_KRATOS_PUBLIC_HOST
              name: pl-ory-service-config
        image: gcr.io/pixie-oss/pixie-dev-public/curl:1.0
        name: kratos-wait
      restartPolicy: Never
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
      - name: certs
        secret:
          secretName: service-tls-certs