apiVersion: v1
kind: Service
metadata:
  labels:
    app: pl-cloud
    name: kratos
  name: kratos
spec:
  ports:
  - name: public
    port: 4433
    targetPort: 4433
  - name: admin
    port: 4434
    targetPort: 4434
  selector:
    app: pl-cloud
    name: kratos