apiVersion: v1
kind: Service
metadata:
  labels:
    app: pl-cloud
  name: profile-service
spec:
  clusterIP: None
  ports:
  - name: tcp-http2
    port: 51500
    protocol: TCP
    targetPort: 51500
  selector:
    app: pl-cloud
    name: profile-server
  type: ClusterIP