apiVersion: v1
data:
  hydra.yml: |
    # All URLS must be set in the environment variables instead of config.
    serve:
      cookies:
        same_site_mode: Strict

    oidc:
      subject_identifiers:
        supported_types:
          - pairwise
          - public
kind: ConfigMap
metadata:
  labels:
    app: pl-cloud
  name: hydra-config
---
apiVersion: v1
data:
  PL_AUTH_CLIENT_ID: auth-code-client
  PL_AUTH_EMAIL_PASSWORD_CONN: ""
  PL_AUTH_URI: oauth/hydra/oauth2/auth
  PL_OAUTH_PROVIDER: hydra
kind: ConfigMap
metadata:
  labels:
    app: pl-cloud
  name: pl-oauth-config
---
apiVersion: v1
data:
  PL_HYDRA_ADMIN_HOST: https://hydra.plc.svc.cluster.local:4445
  PL_HYDRA_PUBLIC_HOST: https://hydra.plc.svc.cluster.local:4444
  PL_HYDRA_SERVICE: hydra.plc.svc.cluster.local:4444
  PL_KRATOS_ADMIN_HOST: http://kratos.plc.svc.cluster.local:4434
  PL_KRATOS_PUBLIC_HOST: http://kratos.plc.svc.cluster.local:4433
  PL_KRATOS_SERVICE: kratos.plc.svc.cluster.local:4433
kind: ConfigMap
metadata:
  labels:
    app: pl-cloud
  name: pl-ory-service-config