apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pl-cloud
    name: hydra
  name: hydra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pl-cloud
      name: hydra
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pl-cloud
        name: hydra
    spec:
      containers:
      - args:
        - serve
        - -c
        - /etc/config/hydra/hydra.yml
        - all
        env:
        - name: PL_POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              key: PL_POSTGRES_USERNAME
              name: pl-db-secrets
        - name: PL_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PL_POSTGRES_PASSWORD
              name: pl-db-secrets
        - name: OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT
          valueFrom:
            secretKeyRef:
              key: OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT
              name: pl-hydra-secrets
        - name: SECRETS_SYSTEM
          valueFrom:
            secretKeyRef:
              key: SECRETS_SYSTEM
              name: pl-hydra-secrets
        - name: DSN
          value: postgres://$(PL_POSTGRES_USERNAME):$(PL_POSTGRES_PASSWORD)@$(PL_POSTGRES_HOSTNAME):$(PL_POSTGRES_PORT)/$(PL_POSTGRES_DB)?sslmode=disable&max_conns=20&max_idle_conns=4
        - name: SERVE_TLS_CERT_PATH
          value: /certs/server.crt
        - name: SERVE_TLS_KEY_PATH
          value: /certs/server.key
        - name: PL_WORK_DOMAIN
          value: work.$(PL_DOMAIN_NAME)
        - name: PL_OAUTH_DOMAIN
          value: $(PL_WORK_DOMAIN)/oauth
        - name: HYDRA_URL
          value: https://$(PL_OAUTH_DOMAIN)/hydra
        - name: URLS_CONSENT
          value: https://$(PL_OAUTH_DOMAIN)/auth/hydra/consent
        - name: URLS_LOGIN
          value: https://$(PL_WORK_DOMAIN)/api/auth/oauth/login
        - name: URLS_LOGOUT
          value: https://$(PL_OAUTH_DOMAIN)/logout
        - name: URLS_SELF_PUBLIC
          value: $(HYDRA_URL)
        - name: URLS_SELF_ISSUER
          value: $(HYDRA_URL)
        envFrom:
        - configMapRef:
            name: pl-db-config
        - configMapRef:
            name: pl-domain-config
        image: oryd/hydra:v1.9.2-sqlite
        name: server
        ports:
        - containerPort: 4444
        - containerPort: 4445
        - containerPort: 5555
        resources: {}
        volumeMounts:
        - mountPath: /etc/config/hydra
          name: config
        - mountPath: /certs
          name: certs
      initContainers:
      - args:
        - migrate
        - -c
        - /etc/config/hydra/hydra.yml
        - sql
        - -e
        - --yes
        env:
        - name: PL_POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              key: PL_POSTGRES_USERNAME
              name: pl-db-secrets
        - name: PL_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PL_POSTGRES_PASSWORD
              name: pl-db-secrets
        - name: OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT
          valueFrom:
            secretKeyRef:
              key: OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT
              name: pl-hydra-secrets
        - name: SECRETS_SYSTEM
          valueFrom:
            secretKeyRef:
              key: SECRETS_SYSTEM
              name: pl-hydra-secrets
        - name: HYDRA_DATABASE
          value: hydra
        - name: DSN
          value: postgres://$(PL_POSTGRES_USERNAME):$(PL_POSTGRES_PASSWORD)@$(PL_POSTGRES_HOSTNAME):$(PL_POSTGRES_PORT)/$(PL_POSTGRES_DB)?sslmode=disable&max_conns=20&max_idle_conns=4
        envFrom:
        - configMapRef:
            name: pl-db-config
        image: oryd/hydra:v1.9.2-sqlite
        name: migrate
        volumeMounts:
        - mountPath: /etc/config/hydra
          name: config
      restartPolicy: Always
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
      - configMap:
          items:
          - key: hydra.yml
            path: hydra.yml
          name: hydra-config
        name: config
      - name: certs
        secret:
          secretName: service-tls-certs