apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: pl-cloud
    component: cloud-deps
  name: plc:nats-server
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - '*'