apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: pl-cloud
    component: cloud-deps
  name: nats-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: pl-cloud
    component: cloud-deps
  name: nats