apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: pl-cloud
    component: cloud-deps
    name: pl-nats
  name: pl-nats
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pl-cloud
      component: cloud-deps
      name: pl-nats
  serviceName: pl-nats
  template:
    metadata:
      labels:
        app: pl-cloud
        component: cloud-deps
        name: pl-nats
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - pl-nats
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - command:
        - nats-server
        - --config
        - /etc/nats-config/nats.conf
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_ADVERTISE
          value: $(POD_NAME).pl-nats.$(POD_NAMESPACE).svc
        image: nats:2.4.0-alpine3.14
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - /nats-server -sl=ldm=/var/run/nats/nats.pid && /bin/sleep 60
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
        name: pl-nats
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 7422
          name: leafnodes
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        - containerPort: 7777
          name: metrics
        readinessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /etc/nats-config
          name: config-volume
        - mountPath: /etc/nats-server-tls-certs
          name: nats-server-tls-volume
        - mountPath: /var/run/nats
          name: pid
      shareProcessNamespace: true
      terminationGracePeriodSeconds: 60
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
      - name: nats-server-tls-volume
        secret:
          secretName: service-tls-certs
      - configMap:
          name: nats-config
        name: config-volume
      - emptyDir: {}
        name: pid