apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: pl-cloud
  name: pl-kuberesolver-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pl-kuberesolver-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: plc