apiVersion: v1
kind: Service
metadata:
  labels:
    app: pl-cloud
  name: scriptmgr-service
spec:
  ports:
  - name: tcp-http2
    port: 52000
    protocol: TCP
    targetPort: 52000
  selector:
    app: pl-cloud
    name: scriptmgr-server
  type: ClusterIP