apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pl-cloud
    db: pgsql
  name: indexer-server
spec:
  selector:
    matchLabels:
      app: pl-cloud
      name: indexer-server
  template:
    metadata:
      annotations:
        prometheus.io/port: "51800"
        prometheus.io/scheme: https
        prometheus.io/scrape: "true"
      labels:
        app: pl-cloud
        monitoring.gke.io/scrape: "true"
        name: indexer-server
    spec:
      containers:
      - env:
        - name: PL_JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              key: jwt-signing-key
              name: cloud-auth-secrets
        - name: PL_VZMGR_SERVICE
          valueFrom:
            configMapKeyRef:
              key: PL_VZMGR_SERVICE
              name: pl-service-config
        - name: PL_ES_URL
          value: {{ include "configMapValue" .Values.elasticsearch.connectionUrl }}
        - name: PL_ES_CA_CERT
          value: /certs/ca.crt
        - name: PL_ES_PASSWD
          valueFrom:
            secretKeyRef:
              name: elastic-config-credentials
              key: password
        envFrom:
        - configMapRef:
            name: pl-indexer-config
        - configMapRef:
            name: pl-tls-config
        - configMapRef:
            name: pl-domain-config
        - configMapRef:
            name: pl-errors-config
            optional: true
        image: gcr.io/pixie-oss/pixie-prod/cloud/indexer_server_image:latest
        livenessProbe:
          httpGet:
            path: /healthz
            port: 51800
            scheme: HTTPS
        name: indexer-server
        ports:
        - containerPort: 51800
          name: http2
        - containerPort: 51801
          name: metrics-http
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /healthz
            port: 51800
            scheme: HTTPS
          periodSeconds: 15
        volumeMounts:
        - mountPath: /certs
          name: certs
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
      - name: certs
        secret:
          secretName: service-tls-certs