apiVersion: v1
kind: Service
metadata:
  labels:
    app: pl-cloud
  name: auth-service
spec:
  clusterIP: None
  ports:
  - name: tcp-http2
    port: 50100
    protocol: TCP
    targetPort: 50100
  selector:
    app: pl-cloud
    name: auth-server
  type: ClusterIP